import React from "react";
import Repo from "@/components/Repo";
import Repodir from "@/components/Repodir";
import { Suspense } from "react";

export const metadata = {
  title: "Repo",
  description: "Generated by create next app",
};

async function RepoPage({ params: { name } }) {
  return (
    <div className="card">
      <Suspense fallback={<div>Loading Repo...</div>}>
        <Repo name={name} />
      </Suspense>
      <Suspense fallback={<div>Loading RepoDir...</div>}>
        <Repodir name={name} />
      </Suspense>
    </div>
  );
}

export default RepoPage;
