export const metadata = {
  title: "About Page",
  description: "Generated by create next app",
};

function About() {
  return (
    <div>
      <h1>About</h1>
      <p>
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quis minus
        necessitatibus nisi saepe assumenda, quaerat ullam ipsam. Illo
        consequuntur nesciunt saepe eaque error dignissimos quas sapiente
        incidunt. Aliquam voluptas reiciendis quis rem porro, adipisci neque,
        possimus non officiis corrupti, mollitia temporibus quisquam et at
        consequuntur quod unde facilis impedit quasi commodi! Eveniet, dolorum
        quas maxime voluptates ad veritatis itaque expedita! Non ducimus magnam
        cupiditate porro, in soluta commodi iste velit voluptas quasi aliquid
        ipsam. Fugit sit eveniet voluptas odio dignissimos molestias nemo minima
        iure cumque ut qui natus, commodi saepe vitae delectus harum praesentium
        sint at pariatur earum excepturi autem laborum! Odio reprehenderit
        maxime, magni incidunt aut quia ea velit recusandae ex. Sit, tempora ea,
      </p>
    </div>
  );
}

export default About;
