export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

async function page() {
  return (
    <div>
      <h1>Search</h1>
      <form action="">
        <input
          className="homeinput"
          type="text"
          placeholder="Search repositories"
        />
        <button className="inp-btn">Search</button>
      </form>
    </div>
  );
}

export default page;
