import React from "react";
import { FaStar, FaCodeBranch, FaEye } from "react-icons/fa";
import Link from "next/link";
export const metadata = {
  title: "Code Page",
  description: "Generated by create next app",
};

export const fetchRepos = async () => {
  const request = await fetch("https://api.github.com/users/akhmedovms/repos");
  const repos = await request.json();
  repos.sort((a, b) => new Date(b.created_at) - new Date(a.created_at));
  return repos;
};

async function PageRepos() {
  const repos = await fetchRepos();

  return (
    <div>
      <h1>All Repositories</h1>
      <ul className="repo-list">
        {repos.map((repo) => {
          return (
            <li key={repo.id}>
              <Link href={`/code/repo/${repo.name}`}>
                <h3>{repo.name}</h3>
                <p>{repo.description}</p>
                <p>Visitibily: {repo.visibility}</p>
                <div className="repo-details">
                  <span>
                    <FaStar /> {repo.stargazers_count}
                  </span>
                  <span>
                    <FaCodeBranch /> {repo.forks_count}
                  </span>
                  <span>
                    <FaEye /> {repo.watchers_count}
                  </span>
                </div>
              </Link>
            </li>
          );
        })}
      </ul>
    </div>
  );
}

export default PageRepos;
